# Inspired from Cartopy conf
version: 2.1

apt-run:  &apt-install
  name: Install apt packages
  command: |
    apt-get -qq update
    apt-get install -y \
      make
      # gcc \
      # g++ \

orbs:
  python: circleci/python@0.2.1

env-run:  &env-setup
  name: Setup conda environment
  command: |
    conda config --set always_yes yes --set changeps1 no --set show_channel_urls yes
    conda create -n test-environment python=$PYTHON_VERSION
    conda config --add channels conda-forge

deps-run: &deps-install
  name: Install python dependencies
  command: |
    conda install -n test-environment --quiet \
        appdirs \
        cartopy \
        cmocean \
        configobj \
        ipython \
        ipykernel \
        jupyter_client \
        matplotlib-base \
        numba \
        nbsphinx \
        pandas \
        scipy \
        "xarray>=0.17" \
        sphinx \
        sphinx-autosummary-accessors \
        sphinx_rtd_theme \
        sphinx-argparse \
        sphinxcontrib-programoutput
    conda list -n test-environment

cp-run: &cp-install
  name: Install xoa
  command: |
    source activate test-environment
    pip install -ve .

doc-run: &doc-build
  name: Build documentation
  command: |
    source activate test-environment
    cd doc
    make html

jobs:
  docs-python3:
    docker:
      - image: continuumio/miniconda3:latest
    steps:
      - checkout
      - run: *apt-install
      - run:
          <<: *env-setup
          environment:
            PYTHON_VERSION: 3
      - run: *deps-install
      - run: *cp-install
      - run: *doc-build
      - store_artifacts:
          path: doc/_build/html

workflows:
  version: 2
  build:
    jobs:
      - docs-python3:
          filters:
            branches:
              ignore:
                - gh-pages

